### ISSUE TITLE
Log: WARNING ClimateDevice is deprecated

### ISSUE THREAD

**Issue by artbrayko** [syssi/xiaomi_airconditioningcompanion#105]
In latest versions of Home Assistant, a message appears in the logs:
WARNING. ClimateDevice is deprecated, modify XiaomiAirConditioningCompanion to extend ClimateEntity

**Comment by anhnvme** [comment]
Replace ClimateDevice to ClimateEntity at all *.py file. It's work

**Comment by anhnvme** [comment]
#106  fixed
