### ISSUE TITLE
ClimateDevice is deprecated, modify XiaomiAirConditioningCompanion to extend ClimateEntity

### ISSUE THREAD

**Issue by SPEC1AL1ST** [syssi/xiaomi_airconditioningcompanion#112]
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:553
Integration: Климат (documentation, issues)
First occurred: 19:58:17 (1 occurrences)
Last logged: 19:58:17

ClimateDevice is deprecated, modify XiaomiAirConditioningCompanion to extend ClimateEntity

**Comment by syssi** [comment]
Fixed by #106
