### ISSUE TITLE
导致HA后台进不去，显示加载中，一直在转圈

### ISSUE THREAD

**Issue by 523295116** [syssi/xiaomi_airconditioningcompanion#115]
删除了配置文件里空调伴侣的代码就能进去了。 下面是日志。 不知道有没有人遇到这个问题。
我是斐讯N1刷F大的openwrt，然后在docker里安装的。版本是 0.116.4
Logger: homeassistant.loader
Source: loader.py:440
First occurred: 下午9:18:07 (1 occurrences)
Last logged: 下午9:18:07

You are using a custom integration for xiaomi_miio_airconditioningcompanion which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

2020-10-27 21:18:07 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miio_airconditioningcompanion which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by keniji** [comment]
Not sure if syssi can read Chinese... So I think this is the same issue as #114 and let's discuss this issue there :)

**Comment by 523295116** [comment]
> 不知道syssi是否可以阅读中文...所以我认为这与[＃114](https://github.com/syssi/xiaomi_airconditioningcompanion/issues/114)是相同的问题，让我们在这里讨论这个问题:)
> 
> 我也遇到这个问题……不知道大佬是不是懂中文，我看到114号issue也是这个问题，所以我还是去那边讨论了哈哈……

同0.116.4的但是安装环境不同，有人可以正常使用。    我把空调伴侣的配置文件放在packages或者直接写进configuration.yaml都是同样的问题， HA的后台会进不去一直加载中。。。 不知道啥问题，

**Comment by syssi** [comment]
I cannot read chinese. This is a duplicate. I will care about #114 soonish.

**Comment by 523295116** [comment]
> 我不会看中文。这是重复项。我很快会关心[＃114](https://github.com/syssi/xiaomi_airconditioningcompanion/issues/114)。
Connecting the air conditioner partner to the home assistant will cause the web background to be loaded all the time. Just delete the configuration file of the air conditioner partner. I hope the author knows what the problem is. thank

**Comment by syssi** [comment]
Please update the custom component. The issue is fixed!
