### ISSUE TITLE
Both home Assistant and Mijia APP responded to the operation, but the air conditioner did not receive infrared instruction

### ISSUE THREAD

**Issue by 523295116** [syssi/xiaomi_airconditioningcompanion#118]
Logger: homeassistant.loader Source: loader.py:463 First occurred: 下午7:09:54 (2 occurrences) Last logged: 下午7:09:57  You are using a custom integration for xiaomi_miio_airconditioningcompanion which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant. You are using a custom integration for iphonedetect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by syssi** [comment]
If your AC isn't properly supported by the acpartner (firmware) / cannot controlled via the Mi Home app this component cannot improve the situation. This is the background: The Mi Home app is used to "provision" the acpartner (f.e. a AC specific remote control command set is uploaded) once. As soon the provisioning is complete this custom component can call some actions to trigger remote control commands from the uploaded set. If there are no working remote control commands this component cannot work.
