### ISSUE TITLE
is there away to get token offline?

### ISSUE THREAD

**Issue by JohnChu101** [syssi/xiaomi_airconditioningcompanion#122]
I dont want to connect the device into the internet or the mobile app. is there a way to get token offline?

**Comment by LiangZugeng** [comment]
There is a XiaoMi cloud token retriever which uses your XiaoMi online account to get tokens from XiaoMi cloud services.

See https://www.home-assistant.io/integrations/xiaomi_miio#xiaomi-cloud-tokens-extractor

**Comment by syssi** [comment]
I'm not aware of a solution to provision a device without **temporary** cloud connection.
