### ISSUE TITLE
The following components and platforms could not be set up

### ISSUE THREAD

**Issue by armasb** [syssi/xiaomi_airconditioningcompanion#14]
Hello, I got error message like this:

"The following components and platforms could not be set up
- climate.xiaomi_miio
Please check your config."

Here's my config.yaml

climate:
  - platform: xiaomi_miio
    name: Aqara Air Conditioning Companion
    host: 192.168.1.107
    token: **mytoken**
    target_sensor: sensor.temperature_158d0001f53706
    scan_interval: 60

I'm very beginner with this so please help me :(
Thanks

**Comment by syssi** [comment]
Sorry for the late response. Did you get it working?

**Comment by armasb** [comment]
Ah yes, that's a silly beginner mistake, I just simply re-install the component and it's working now. Just wondering if I can use the gateway function too or not?

**Comment by syssi** [comment]
Which revision of the device do you own (v1, v2, v3)?

**Comment by armasb** [comment]
It's v3

**Comment by syssi** [comment]
You are a lucky guy! The recent gateway firmware of the v3 introduces the LAN protocol. This Home Assistant PR introduces the device support for your device at the xiaomi_aqara component: https://github.com/home-assistant/home-assistant/pull/13540/files

**Comment by armasb** [comment]
Nice!
One thing, how do i set it up to work with my door sensor?
Also alexa didn't detect my aqara ac companion, is alexa can't detect all custom component?

Thanks

**Comment by syssi** [comment]
Please describe your setup and what do you try to achieve?

**Comment by armasb** [comment]
oh sorry I want to connect my door sensor to aqara air condition companion with home assistant

**Comment by syssi** [comment]
1. You should wait until your device is official supported by Home Assistant -> Merge of the Pull Request. If you cannot wait anymore: You have to use this feature branch.
2. This custom component doesn't provide support for the gateway function! You have to use the `xiaomi_aqara` component.
3. Setup the `xiaomi_aqara` component. A encryption key is needed (read the manual!): https://www.home-assistant.io/components/xiaomi_aqara/
4. Press the button of your gateway three times and the pairing button of your door sensor once. A chinese voice will confirm the successful pairing
5. Restart Home Assistant. The paired device will show up as a `binary_sensor` entity now.
6. Read the manual how to setup automations: https://www.home-assistant.io/components/binary_sensor.xiaomi_aqara/#door-andor-window
