### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by jjcszxh** [syssi/xiaomi_airconditioningcompanion#140]
xiaomi_airconditioningcompanionThe plug-in turns on the air conditioner, and the panel does not display the temperature.  Attribute: led is false.

**Comment by syssi** [comment]
Could you provide more details?

**Comment by jjcszxh** [comment]
I didn't see any errors in the log. Didn't I start the debug of this integration?

**Comment by jjcszxh** [comment]
I didn't see any errors in the log. Didn't I start the debug of this integration?
