### ISSUE TITLE
My home assistant can't find this add-on

### ISSUE THREAD

**Issue by MrTvistYT** [syssi/xiaomi_airconditioningcompanion#143]
I have that problem. When I input link on this repository. It gives me: _"Invalid Add-on repository!"_

<img width="770" alt="Записати" src="https://user-images.githubusercontent.com/85845288/149772213-1045cafd-beae-4a53-afd2-8f4b195182df.PNG">

In logs, you can see:
`22-01-17 14:39:33 ERROR (MainThread) [supervisor.store] https://github.com/syssi/xiaomi_airconditioningcompanion/ is not a valid add-on repository`

**Comment by syssi** [comment]
This custom component isn't an "Add-on". Please use "HACS" to install this custom component.
