### ISSUE TITLE
Hitachi AC support

### ISSUE THREAD

**Issue by thundergreen** [syssi/xiaomi_airconditioningcompanion#15]
Hi all. I just ordered two of v2 xiaomi devices but couldn't find a supported ac list. Is there a list available somewhere? I have Hitachi ac at hone and wanna use this component for it

**Comment by syssi** [comment]
Could you try to use the Mi Home app for setup & testing? Which device did you select at the app to work with your AC? Could you provide the response of:

```
mirobo --ip <ip> --token <token> "get_model_and_state" "[]"
```

**Comment by thundergreen** [comment]
(homeassistant) hass@home-assistant:~$ mirobo --ip 192.168.1.5 --token b67708efaa2564ff3bddeaa5d87cb2f5 "get_model_and_state" "[]"
Usage: mirobo [OPTIONS] COMMAND [ARGS]...

Error: No such command "get_model_and_state".

**Comment by syssi** [comment]
The correct command is:

```
mirobo --ip <ip> --token <token> raw_command get_model_and_state "[]"
```

**Comment by thundergreen** [comment]
I added token from gateway.. Should I add the ac device as gateway?

**Comment by thundergreen** [comment]
I got the right ac in the app ..yeahhh it was not under "h" but somewhere else ...now I need to know how to add this to has. Could u guide me?

**Comment by thundergreen** [comment]
2018-05-08 12:13:31 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.aqara_air_conditioning_companion fails
Traceback (most recent call last):
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/home/hass/.homeassistant/custom_components/climate/xiaomi_miio.py", line 212, in async_update
    ATTR_LED: state.led,
  File "/home/hass/homeassistant/lib/python3.6/site-packages/miio/airconditioningcompanion.py", line 106, in led
    return 'on' if (int(self.data[1][8:9]) == Led.On.value) else 'off'
ValueError: invalid literal for int() with base 10: 'A'

**Comment by syssi** [comment]
```
$ mirobo --ip 192.168.1.5 --token d0b0d861f217c9afd4fb8ee246d12053 raw_command get_model_and_state "[]"
Sending cmd get_model_and_state with params []
['010502070001123201', '010120140100011232', '0']
```

**Comment by thundergreen** [comment]
Can be closed. Using mi app v 5.0.0 solves problem to get token from ac partner by clicking about and at the bottom the version number several times
