### ISSUE TITLE
添加到hacs后在集成页搜不到相应集成

### ISSUE THREAD

**Issue by chantAria** [syssi/xiaomi_airconditioningcompanion#154]
已经添加到hacs了,在terminal中的custom_components中也可以看到xiaomi_miio_airconditioningcompanion文件夹,但在集成页面添加集成时找不到这个集成,强制刷新之后也不行(我的集成中有一个Xiaomi Miot Auto不知道有没有影响),但Xiaomi  Miot Auto没有红外功能

**Comment by saury** [comment]
看[readme](https://github.com/syssi/xiaomi_airconditioningcompanion/blob/develop/README.md#setup), 要自己写到`configuration.yaml`里。
