### ISSUE TITLE
Fit KTBL11LM

### ISSUE THREAD

**Issue by ArronYin** [syssi/xiaomi_airconditioningcompanion#16]
Aqara Air has a new product model of KTBL11LM,  The appearance is the same as KTBL01LM   plugin support?

**Comment by syssi** [comment]
This is the most recent hardware revision (acpartner.v3) of the device. Please order this version if possible!

**Comment by clyevo** [comment]
i know the infrared can be supported by hass
but is the gateway supported by hass?
