### ISSUE TITLE
Integration error: cliamte - Integration 'cliamte' not found.

### ISSUE THREAD

**Issue by royi1000** [syssi/xiaomi_airconditioningcompanion#163]
configuration.yaml:
cliamte:
 - platform: xiaomi_miio_airconditioningcompanion
   name: Aqara AC LR
   host: 192.168.1.160
   token:****
   target_sensor: ****
   scan_interval: 60

when checking configuration I'm getting:
Integration error: cliamte - Integration 'cliamte' not found.

**Comment by syssi** [comment]
Did you see the typo in `cliamte` vs `climate`?
