### ISSUE TITLE
Home Assistant 0.74.2 miio-4.0 get an error

### ISSUE THREAD

**Issue by txlihao** [syssi/xiaomi_airconditioningcompanion#30]
File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 311, in _async_add_entity
    'Invalid entity id: {}'.format(entity.entity_id))
homeassistant.exceptions.HomeAssistantError: Invalid entity id: climate.

**Comment by syssi** [comment]
Please change the name of the device. Try to use latin characters only.

https://github.com/home-assistant/home-assistant/issues/13734
https://community.home-assistant.io/t/friendly-name-with-chinese-characters-got-error-is-this-a-bug/9960/6

**Comment by txlihao** [comment]
i was use  aircondition,not chinese char
