### ISSUE TITLE
Please add an new function that can control(switch on/off) the electric source

### ISSUE THREAD

**Issue by Uptobillion** [syssi/xiaomi_airconditioningcompanion#31]

**Comment by syssi** [comment]
Which hardware version of the device do you own?

**Comment by Uptobillion** [comment]
acpartner.v3

**Comment by syssi** [comment]
ref. https://github.com/rytilahti/python-miio/issues/337

**Comment by syssi** [comment]
At the moment I'm not aware of a miIO command to toggle the internal relay.

**Comment by hsie** [comment]
Hi, thanks and I now get the command from the wireshark, and while when I tried to send the command to the ac partner via Packet Sender, it doesn't work, just wonder how can I send the command directly via ubuntu, as I think the reason behind may be caused by token.

Attached are json files that I saved from turning on/off the power, file 1& 2 are got from turning on, while file 3 & 4 are for turning off.

I am not sure why it sent 2 udp packets every time when turning on or off.

Thanks in advance!

[ac.zip](https://github.com/syssi/xiaomi_airconditioningcompanion/files/2591528/ac.zip)

**Comment by syssi** [comment]
@hsie The data is encrypted. Could you provide your token, too? 

cp. https://github.com/rytilahti/python-miio/blob/master/miio/protocol.py
cp. https://github.com/rytilahti/python-miio/blob/master/miio/device.py#L259-L260

**Comment by syssi** [comment]
Could you try these commands?

```
miiocli device --ip DEVIP --token DEVTOKEN raw_command toggle_plug '["on"]'
miiocli device --ip DEVIP --token DEVTOKEN raw_command toggle_plug '["off"]'
```

**Comment by syssi** [comment]
This should provide the state of the socket

```
miiocli device --ip DEVIP --token DEVTOKEN raw_command get_device_prop '["lumi.0", "plug_state"]'
```

**Comment by hsie** [comment]
you are really great! it works now.

and one more question, how to use the command line in the switch template?  so that I can setup a switch, thanks again for your kindness!

**Comment by hsie** [comment]
the token for this ac partner is 203dca9dfd709524ab7d6fd22f026257

**Comment by syssi** [comment]
Could you provide the output of this command:

```
miiocli device --ip DEVIP --token DEVTOKEN raw_command get_device_prop '["lumi.0", "plug_state"]'
```

I want to make sure we can retrieve the current state.

**Comment by syssi** [comment]
I will extend the component as far as the new version of python-miio is released.

**Comment by hsie** [comment]
the output is as below.
------------
root@hp:~# miiocli device --ip 192.168.2.35 --token 203dca9dfd709524ab7d6fd22f026257 raw_command get_device_prop '["lumi.0", "plug_state"]'
Running command raw_command
['off']

**Comment by syssi** [comment]
I haven't implemented the feature yet.

**Comment by syssi** [comment]
I've extended this custom component: https://github.com/syssi/xiaomiplug/

```
# configuration.yaml

switch:
  - platform: xiaomi_miio
    name: AC Partner V3 Socket
    host: 192.168.130.59
    token: b7c4a758c251955d2c24b1d9e41ce47d
    model: lumi.acpartner.v3
```

**Comment by hsie** [comment]
After upgrading to ha 0.88, the switch for acparter v3 doesn't work, below is the error message, would appreciate it if you can have a look, thanks in advance!

Unsupported device found! Please create an issue at https://github.com/rytilahti/python-miio/issues and provide the following data: lumi.acpartner.v3

**Comment by vcheng99** [comment]
thanks for the work, that's what I wanted.

but I got this error:
Configuration invalid 
Check config 
Invalid config for [switch.xiaomi_miio]: value is not allowed for dictionary value @ data['model']. Got 'lumi.acpartner.v3'. (See ?, line ?). Please check the docs at https://home-assistant.io/components/switch.xiaomi_miio/

I am using HA 0.88.2
put switch.py under config\custom_components\xiaomi_miio
switch:
  - platform: xiaomi_miio
    name: AC Partner V3 Socket Living Room
    host: 192.168.30.94
    token: e6485a97d3fcbc123508db716708fae8
    model: lumi.acpartner.v3

please help
