### ISSUE TITLE
[Question] Not able to retrieve Token

### ISSUE THREAD

**Issue by aimartin** [syssi/xiaomi_airconditioningcompanion#32]
I'm not able to retrieve the token anymore from the MiHome app, I did it in the past, but I'm not able to do it following the instructions from HomeAssistant page, I'm using China Mainland and English, I select the gateway, click on the three dots up right, but the "about" button is not there, so I'm not able to enable/disable lan_mode nor to see the password and token. I tried with IOS and with Android.

Is there any other way to get it?

Cheers

**Comment by syssi** [comment]
Please downgrade the MiHome App (Android): https://www.home-assistant.io/components/vacuum.xiaomi_miio/#retrieving-the-access-token
