### ISSUE TITLE
Google home speaker responds 'that mode isn't available for the bedroom AC' when told to turn on the thermostat

### ISSUE THREAD

**Issue by yuqian90** [syssi/xiaomi_airconditioningcompanion#37]
I set up a xiaomi_miio entity for my AC and I can use the web front end to control the On/Off of the AC. I named the entity 'bedroom AC'. I also have google home connected to my home assistant via the google_assistant component. I can say things like 'okay google, turn on the light' to the google home speaker and it can control the lights via home assistant. However, when I say 'okay google, turn on the bedroom AC', google speaker will reply 'Sorry, I don't know how to help with that'. If I say 'okay google, turn on the thermostat', google speaker replies 'Sorry, that mode isn't available for the bedroom AC'.

So it seems home assistant is able to control the AC. And google home is able to control devices on home assistant, but not the AC. Is there some issue with xiaomi_airconditioningcompanion that prevents google home from doing the voice control?

The device I use to control the AC is a lumi.acpartner.v2. My AC is not physically plugged to the power socket on the acpartner. So in Mi Home, I turned off the option 'Aircon On / off auto detection' (translated from Chinese, it's an option for the acpartner in Mi Home App). My google home is connected to home assistant using the setup described in https://www.home-assistant.io/components/google_assistant/

**Comment by flexyneat** [comment]
HI,
I'm experiencing the same issue. Just like the OP, my AC is not physically plugged into the AC partner and i'm using the lumi.acpartner.v3 on the latest firmware (just updated last night). Control works fine via home assistant but google home says "sorry, that mode isn't available for the Living Room AC". 

Google home is connected via cloud (nabucasa.com) subscription

**Comment by syssi** [comment]
I've updated the component. If we've some luck the operation mode and temperature should work now.

**Comment by flexyneat** [comment]
> I've updated the component. If we've some luck the operation mode and temperature should work now.

Ok, thanks.
Just got to work.... will test when i get home this evening

**Comment by ntcong** [comment]
turning on/off seems to work now after update, but I can't find a way to turning cool to heat or auto. It's always turn on cool mode with google assistant. Don't know if it's home assistant problem or the climate custom component

**Comment by flexyneat** [comment]
Issue seems to still be occurring on HA 0.92.2, cant even turn off or on.
