### ISSUE TITLE
Swing Mode Definition

### ISSUE THREAD

**Issue by cxlwill** [syssi/xiaomi_airconditioningcompanion#4]
As far as I know, actually `Swing Mode` here doesn't represent for  direction `up` and `down`. It should be recognized as boolean value for `on` and `off`. Is it defined by Home Assistant's climate component? If so maybe we can add another 2 modes for `on` and `off`?

**Comment by syssi** [comment]
The climate interface defines just a list of values. The demo component provides this example:

```
self._swing_list = ['Auto', '1', '2', '3', 'Off']
```

Do you know the possible values of the response payload?

https://github.com/rytilahti/python-miio/blob/master/miio/airconditioningcompanion.py#L114

**Comment by cxlwill** [comment]
Here's the screenshot of this device in MiHome app: 
![img_5707](https://user-images.githubusercontent.com/13537549/36421000-d5adbbfe-1671-11e8-920b-bc4b8160b56e.PNG)

For swing mode, I suggest only 'on' and 'off' , meaning automatically swing or not. Although it may become complex when some models support different mode of swing like up-down, left-right. 

For payload, do you mean full IR code? Well, I think the idea in original component is that:
1. It offers some built-in control codes and there are some general characters of codes like fourth number meaning `swing mode`. 
2. If your air conditioner is different from built-in supported one then you use IR Code learner(`Chuangmi_ir remote`) to learn your own codes  and add it to `config`.

Furthermore, the reason of this method is that Xiaomi actually offers huge built-in IR code database in MiHome app or Xiaomi Cloud I guess. When you add this partner in Mihome app, you can choose your conditioner's brand and type, then most of time, it is supported automatically. No code learning needed.

**Comment by syssi** [comment]
Do you have a rooted android device and are you able to provide the ac partner plugin of the MiHome app? I can provide some instructions (adb calls).

**Comment by cxlwill** [comment]
Yes, I would like to do it.

**Comment by syssi** [comment]
Please install the mihome app and login into your account. With each registered device (f.e. the ac partner) the app does install a plugin (apk) I'm interested in. The APKs of the plugins are located here normally:

```bash
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk
```

Could you provide a complete copy of the folder? 

```bash
adb root
adb connect 192.168.132.24
adb pull /data/data/com.xiaomi.smarthome/files/plugin/install/mpk
zip -r plugins.zip mpk
```

This is the content in my case:

```bash
hammerhead:/data # find ./data/com.xiaomi.smarthome/files/plugin/install/mpk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/com.xiaomi.catalog
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/com.xiaomi.catalog/7
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/com.xiaomi.catalog/7/7.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/com.mijiashop.main
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/com.mijiashop.main/19
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/com.mijiashop.main/19/19.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/com.xiaomi.pinwei
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/com.xiaomi.pinwei/2
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/com.xiaomi.pinwei/2/2.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/108
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/108/10707.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/108/10585.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/229
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/229/7956.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/229/10301.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/107
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/107/8653.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/473
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/473/7490.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/503
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/503/10146.apk
/data/data/com.xiaomi.smarthome/files/plugin/install/mpk/503/10536.apk
```

**Comment by cxlwill** [comment]
Here's mine with the latest MiHome app:

```
mpk/ 
mpk/com.xiaomi.pinwei/ 
mpk/com.xiaomi.pinwei/2/ 
mpk/com.xiaomi.pinwei/2/2.apk 
mpk/com.mijiashop.main/ 
mpk/com.mijiashop.main/19/ 
mpk/com.mijiashop.main/19/19.apk 
mpk/187/ 
mpk/187/3194.apk
mpk/108/ 
mpk/108/8672.apk
mpk/108/10989.apk
mpk/com.xiaomi.catalog/ 
mpk/com.xiaomi.catalog/7/
mpk/com.xiaomi.catalog/7/7.apk
```
As far as I know, Mihome app changed a lot since 5.1.xx. Do I need to use older version app?

**Comment by syssi** [comment]
I need the content of the apk files. :-) Both versions would be awesome.

**Comment by cxlwill** [comment]
OK, here are 2 files:
[plugins-5.0.19.zip](https://github.com/syssi/xiaomi_airconditioningcompanion/files/1740234/plugins-5.0.19.zip)
[plugins-5.1.5.zip](https://github.com/syssi/xiaomi_airconditioningcompanion/files/1740235/plugins-5.1.5.zip)

BTW, the file list of 5.0.19:

```
mpk/
mpk/com.xiaomi.pinwei/
mpk/com.xiaomi.pinwei/2/
mpk/com.xiaomi.pinwei/2/2.apk
mpk/com.mijiashop.main/
mpk/com.mijiashop.main/19/ 
mpk/com.mijiashop.main/19/19.apk
mpk/187/
mpk/187/3194.apk
mpk/108/
mpk/108/8672.apk
mpk/108/10989.apk
mpk/com.xiaomi.catalog/
mpk/com.xiaomi.catalog/7/
mpk/com.xiaomi.catalog/7/7.apk
```

**Comment by syssi** [comment]
It looks like there a two device plugins (187 and 108) installed. 

108: Xiaomi Gateway
187: Xiaomi MiTV 

Does it match with your devices?

**Comment by cxlwill** [comment]
I do have a Gateway and one Mibox which may be recognized as MiTV.

**Comment by syssi** [comment]
Fixed.
