### ISSUE TITLE
The on/off button sometimes doesn't work

### ISSUE THREAD

**Issue by rddkrn** [syssi/xiaomi_airconditioningcompanion#45]
Hello,
I'm very happy with your component. I installed it in Hassio for LG AC. My hardware is acpartner.v3.
I found a problem that sometimes the on/off button doesn't work, after using mi home application or the original ac's remote and trying several times then the on/off button do work again, and this often happens. The first time it's turned on then the operation menu always becomes "ventilate".

I also use Google Home and this component can be connected properly but there is no on/off function

I'm still new to Github, and thank you very much.

**Comment by syssi** [comment]
If possible you shouldn't use the remote control of the AC anymore. The AC partner cannot keep track of the current AC state/setting if you control your AC directly. Did you plug the AC into the AC partner?

**Comment by rddkrn** [comment]
Yes, I plugged the AC into the AC partner.

**Comment by rddkrn** [comment]
I dont know how to enabled or disabled power/load sensing, I cant find this setting everywhere. When I turn on the AC from HA, the operation menu change from cool to ventilate automatically. 
My AC accepted a turn off command from HA by giving beep sound, but not accepted a turn on command (no beep).

**Comment by rddkrn** [comment]
This work very good for the off operation mode. 
I'm still having trouble with the on/off command which sometimes can't work. I added an input_boolean to send on/off commands using climate.xiaomi_miio_send_command, and this way can always be successful.  if possible add this function in the component. 
Thank you for your hard work.
