### ISSUE TITLE
Zigbee thermostat device "lumi.airrtc.tcpecn01"

### ISSUE THREAD

**Issue by bluefoxlee** [syssi/xiaomi_airconditioningcompanion#47]
Sorry if I post at wrong Github project page. Not sure if I should report this under gateway issue or here since it's a Zigbee product. 

I just bought this EigenStone thermostat recently, and it's manufactured by same company as Lumi / Aqara. Wonder how I can contribute miiocli of python-miio data with it. Since it's a zigbee product. 

Thanks in advance.

**Comment by syssi** [comment]
If it's a zigbee device you should use `xiaomi_aqara` (the lumi gateway with LAN protocol enabled). This component (based on the miIO protocol) doesn't support any gateway functions right now.
