### ISSUE TITLE
IR Remote function support

### ISSUE THREAD

**Issue by cxlwill** [syssi/xiaomi_airconditioningcompanion#5]
Another issue, AC partner has IR remote learner inside which supply Air Conditioner IR codes for partner when some AC models unsupported naturally. So we can make use of chuangmi_ir component. Should we add this function into this component or add AC partner support for [IR Remote component](https://github.com/syssi/chuangmi_ir)?

**Comment by syssi** [comment]
We should add AC partner specific features to this component as first step.

This component is obsolete: https://github.com/syssi/chuangmi_ir
And replaced by https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/remote/xiaomi_miio.py

I will merge both components someday because of the intersection.

**Comment by cxlwill** [comment]
For now, I cannot use remote component to learn codes from AC Partner. It is supposed to use different port I guess.

```
Error executing service <ServiceCall remote.xiaomi_miio_learn_command: entity_id=remote.ac_partner, slot=1, timeout=10>
Traceback (most recent call last):
  File "/Users/cxlwill/.homeassistant/deps/lib/python/site-packages/miio/device.py", line 243, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homeassistant/components/remote/xiaomi_miio.py", line 121, in async_service_handler
    yield from hass.async_add_job(device.learn, slot)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/cxlwill/.homeassistant/deps/lib/python/site-packages/miio/chuangmi_ir.py", line 26, in learn
    return self.send("miIO.ir_learn", {'key': str(key)})
  File "/Users/cxlwill/.homeassistant/deps/lib/python/site-packages/miio/device.py", line 273, in send
    return self.send(command, parameters, retry_count - 1)
  File "/Users/cxlwill/.homeassistant/deps/lib/python/site-packages/miio/device.py", line 256, in send
    raise DeviceError(m.data.value["error"])
miio.device.DeviceError: {'code': -32601, 'message': 'Method not found.'}
```

**Comment by syssi** [comment]
The command set is different. The Xiaomi Remote Controller uses

```
miIO.ir_play, miIO.ir_read, miIO.ir_learn
```

The AC partner supports

```
send_cmd, send_ir_code, start_ir_learn, end_ir_learn, get_ir_learn_result
```

**Comment by syssi** [comment]
Could you try to learn a command and provide the output? @liorm0505

```
mirobo --ip <ip-of-your-gateway> --token <your-token> raw_command start_ir_learn "[30]"
# press a key of your remote control
mirobo --ip <ip-of-your-gateway> --token <your-token> raw_command end_ir_learn "[30]"
mirobo --ip <ip-of-your-gateway> --token <your-token> raw_command get_ir_learn_result "[]"
# may be
mirobo --ip <ip-of-your-gateway> --token <your-token> raw_command get_ir_learn_result "[30]"
```
You should be able to replay the learned command (string response of the commands above).

```
mirobo --ip <ip-of-your-gateway> --token <your-token> raw_command send_ir_code "['123123123']"
```

**Comment by ntcong** [comment]
```
pi@raspberrypi:~/homeassistant $ mirobo  raw_command start_ir_learn "[30]"
Sending cmd start_ir_learn with params [30]
['ok']
pi@raspberrypi:~/homeassistant $ mirobo  raw_command end_ir_learn "[30]"
Sending cmd end_ir_learn with params [30]
['ok']
Api@raspberrypi:~/homeassistant $ mirobo raw_command get_ir_learn_result "[30]"
Sending cmd get_ir_learn_result with params [30]
['(null)']
```
Tried the learning command but the result is null

**Comment by syssi** [comment]
What happens if you remove the parameter (30) of the last command?

**Comment by ntcong** [comment]
I tried both and it's still null

**Comment by ntcong** [comment]
Oh so you suppose to start, get the result and then end learn
```
pi@raspberrypi:~ $ mirobo  raw_command start_ir_learn "[30]"
Sending cmd start_ir_learn with params [30]
['ok']
pi@raspberrypi:~ $ mirobo raw_command get_ir_learn_result "[30]"
Sending cmd get_ir_learn_result with params [30]
['FE00000000000000000000000005004E227300550109015C0FC81388220101000101010000000000010000010000000101010101000322010100010101000000000001000001000000010101010100032201010001010100000000000100000100000001010101010004C2']
pi@raspberrypi:~ $ mirobo  raw_command end_ir_learn "[30]"
Sending cmd end_ir_learn with params [30]
['ok']
```

**Comment by syssi** [comment]
It's okay if the code changes every time. It's a recording (like an audio recording just of IR light). Replay a single recording should work. What did you do for a proper recording?

**Comment by syssi** [comment]
Hmmmm. I've no idea.

**Comment by ntcong** [comment]
I tried tcpdump the traffic but can't find the traffic from IR learn, can you send me the IR code you catch and the IR code registered by Mi Home so I can take a look?

**Comment by cnk700i** [comment]
Before capturing, make your phone disconnect to Internet and try again.I think the APP will send command throw server on internet instead of sending command directly to airconditioningcompanion. I can't offer IR code now because I'm not at home.

**Comment by cnk700i** [comment]
get_ir_learn_result:
"FE00000000000000000000000006004222680025002D008500AC015A138843010201020102010201010102010202010201010102020201020102010202010101010101010101010102010101010101020101010102010102010101020201020517"
send_ir_code:
"FE04870000714594701FFF**7f**FF06004227**4e**0025002D008500AC015A138843010201020102010201010102010202010201010102020201020102010202010101010101010101010102010101010101020101010102010102010101020201020517"
get_model_and_state:
["010504870000714501","010000000100007145","0"]

I find two laws.
1.The IR code works after code[22:24] and code[34:36] change, as long as ensure the result of code[22:24] minus code[34:36] equal the previous one. For example, in this IR code, 7f-4e=31(HEX), you can change 4e to 00 as long as change 7f to 31.
2.code[2:14] seems like model strings which appear in the result after sending command
 of "get_model_and_state" to device.

**Comment by syssi** [comment]
@yawor Could you help here?

**Comment by syssi** [comment]
Cool discovery! The meaing of
```
94701FFF7fFF
```
is the last missing piece.

**Comment by syssi** [comment]
```
code = FE + 0487 + 00007145 + 9470 + str2     + str[26:28] + str[28:32] + 27
       FE + 0487 + 00007145 + 9470 + 1FFFxxFF + 06         + 0042       + 27
```

**Comment by yawor** [comment]
@syssi you've missed the "header checksum" byte after "27" in the first line. It's a sum of all previous bytes modulo 256 (basically the same as `sum & 0xFF`). After that is the rest of the original recording.

**Comment by syssi** [comment]
@yawor Thanks for your always great support! :-)

**Comment by yawor** [comment]
@syssi I don't think I have the apk with this plugin. Can you send it to me? I'll try to go deeper and find out what's `this.x`. Let me also know the full qualifier path to the class you've found that code at.

**Comment by syssi** [comment]
@yawor I've sent you a mail (plugin 108).

**Comment by yawor** [comment]
That `0x7f` (dec value 121) byte seems to be some kind of command index or slot. In the code, it's called shortCmd and its starting value seems to be 121. Both the `cq` and `cr` methods in the above decompiled code are called by the callback after running `get_ir_learn_result` command and is provided with the resulting data. The first `String` argument for `cr` method is the result retrieved from the device and second `String` is a value returned by `cq` method. The `cq` method seems to look for a free command slot, starting from value 121 and returns first slot number without a recorded IR command, encoded as a hex string.

I don't know if the device actually cares about that value. I think it's used by the app (it may be stored in the sqlite) and synchronised with Xiaomi servers. I wonder if the device actually stores these IR commands on its flash memory.

**Comment by thundergreen** [comment]
Does this mean that we will soon have learning commands for those devices ?

**Comment by syssi** [comment]
`python-miio` version 0.4.0 is released and brings the foundation for this feature. I will update this component soon.

**Comment by syssi** [comment]
I'm able to turn on/off my AC by some learned infrared command:

```
$ miiocli airconditioningcompanion --ip 192.168.130.83 --token acf23c57a96e37d7a007ac484c1dca63 send_ir_code 010500320000282701 FE0000000000000000000000000500222247003900AA01D003901388320000000100000100000100000100000001000000000000000000000100000000041E
Sending the supplied infrared command
['ok']
```

This feature is near. :-)

**Comment by aimartin** [comment]
I'm really interested in this feature, as I'm not able to pair my AC with the app (I don't know my brand name in chinese...), with MiHome I'm only able to send learned commands.

Apart from that, I'm not able to retrieve the token anymore from the MiHome app, I did it in the past, but I'm not able to do it following the instructions from HomeAssistant page, I'm using China Mainland and English, I select the gateway, click on the three dots up right, but the "about" button is not there, so I'm not able to enable/disable lan_mode nor to see the password and token.

Is there any other way to get it?

Cheers
