### ISSUE TITLE
AC turns off on target temperature update / Hisense AC

### ISSUE THREAD

**Issue by jason5ng32** [syssi/xiaomi_airconditioningcompanion#54]
I have exactly the same problem with this person: https://github.com/syssi/xiaomi_airconditioningcompanion/issues/35#issuecomment-444810245

不管是 v2 还是 v3 的空调伴侣都一样。

**Comment by tzm112** [comment]
一样啊。我的V3也是这样。随便按调整温度还是选择模式都会关闭

**Comment by tzm112** [comment]
my v3 acpartener is always turn off my ac,when my switch tempture  no matter high or low.and witch ac mode is the same thing .sorry my poor english. my ac is hisence

**Comment by syssi** [comment]
@tzm112 Has an Hisense AC (010500070001171701). @jason5ng32 could you provide the AC model identifier of your AC?

**Comment by jason5ng32** [comment]
@syssi Hisense 11797

**Comment by jason5ng32** [comment]
￼￼海信（Hisense）1.5匹 智能 冷暖 一级能效 直流变频 空调挂机（KFR-35GW/A8X860N-A1(1P26)）
