### ISSUE TITLE
Error on HA 0.96.0

### ISSUE THREAD

**Issue by befantasy** [syssi/xiaomi_airconditioningcompanion#67]
the component can't work in HA 0.96.0. 

ERROR INFO:

Platform not found: climate.xiaomi_miio_airconditioningcompanion

**Comment by KangKai1982** [comment]
+1
Looks like they changed the climate integration in 0.96.0 release.

**Comment by jfacevedo80** [comment]
Will the component be updated?

**Comment by fineemb** [comment]
+1

**Comment by zz66** [comment]
same issue

**Comment by syssi** [comment]
Yes. Please give mesome give!

**Comment by vhristev** [comment]
Same issue here.

**Comment by browntownington** [comment]
Hey everyone.
They completely rewrite the climate integration on 0.96
Alot of things were renamed and some changed slightly.
I had a look at updating the custom code myself but thought I'd just sit and be patient.
Let's give @syssi some time to look at what needs updating.

**Comment by flexyneat** [comment]
same issue here,

**Comment by axelburks** [comment]
Same issue here.

**Comment by rflx18** [comment]
no news or workaround on this?»

**Comment by exdee85** [comment]
Same issue here.

**Comment by neykovt** [comment]
Issue confirm !

**Comment by wzwick** [comment]
Commenting to follow
Thanks for jumping on it @syssi

**Comment by plutosherry** [comment]
same error `Platform not found: climate.xiaomi_miio_airconditioningcompanion`

**Comment by claudiu-persoiu** [comment]
+1

**Comment by keniji** [comment]
Thankfully I've checked HA's changlog before upgrading it, then I found they've changed climate integration. Hopefully there will be an update for this integration soon..

**Comment by izmao** [comment]
加油大神，等着您的米下锅呢哈哈

**Comment by ToddTsao** [comment]
New version is work for me. 
HASS 0.96.5

**Comment by rflx18** [comment]
> New version is work for me.
> HASS 0.96.5

and the configuration, can you drop a example of a working setup pls?

**Comment by neykovt** [comment]
work fine. no need to change config.

**Comment by befantasy** [comment]
there is another problem，in new version，the on/off status was disappeared in temperature chart

**Comment by syssi** [comment]
Compatibility added by #69. @befantasy please follow #72.
