### ISSUE TITLE
No AirConditioningCompanionStatus.air_condition_power and _device

### ISSUE THREAD

**Issue by ntcong** [syssi/xiaomi_airconditioningcompanion#8]
The latest version of miio replace air_condition_power with load_power, currently, climate is using both results in an error
`AttributeError: 'XiaomiAirConditioningCompanion' object has no attribute 'air_condition_power'`

Same problem with turn_on and turn_off:
`AttributeError: 'XiaomiAirConditioningCompanion' object has no attribute '_device'`

Also when I tried to set temp:
```
  File "/config/custom_components/climate/xiaomi_miio.py", line 385, in async_set_temperature
    if self._target_temperature < self._target_temperature_low:
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```

I'm trying to set the ac companion with a Mitsubishi Heavy AC, should it work right out the box with the generic template, or do I need to record the IR command?

I'm thinking about getting some debugging, is there any way to run the custom_component headless (without hass.io running)

**Comment by syssi** [comment]
Please use the master branch of python-miio. I updated the attribute names. I will prepare a 0.3.8 release of python-miiio soon.

**Comment by syssi** [comment]
You fixed this one (`AttributeError: 'XiaomiAirConditioningCompanion' object has no attribute '_device'`) by #9. Thanks a lot! The component is in a alpha state and needs to be tested heavily.

**Comment by syssi** [comment]
python-miio 0.3.8 is released. The errors should be gone now.
