### ISSUE TITLE
AC can not be turned off by siri @ 0.98

### ISSUE THREAD

**Issue by schwarzkreuz** [syssi/xiaomi_airconditioningcompanion#81]
After I upadted HA from 0.96 to 0.98, when use siri to turn off the ac, I said "Hey siri, turn off the bedroom's air conditioning", but nothing happended.
Then I went to the dev-tools to see the logs and found that it use a invalid "heat_cool" for hvac mode.

Here is the logs:
Error executing service <ServiceCall climate.set_hvac_mode : entity_id=['climate.air_conditioning_2f'], hvac_mode=heat_cool>
custom_components/xiaomi_miio_airconditioningcompanion/climate.py (ERROR)
ValueError: 'heat_cool' is not a valid OperationMode

Hope it can be fixed and THX.

**Comment by onewaylifestreet** [comment]
Same issue here, any fix?

**Comment by syssi** [comment]
Could you try again and report if the issue still persists?
