### ISSUE TITLE
Xiaomi MIUI11 Lock Screen Issue?

### ISSUE THREAD

**Issue by saish-borkar** [syssi/xiaomi_airconditioningcompanion#91]
Hi, 
After updating to the stable version of #miui11. From few 

days I'm facing weird issue. Whenever I'm trying to login to my phone using the fingerprint then the all the icons are visible but when I try to login using my in or pattern then the wallpaper is overlapping all the icons and making it invisible. Is anyone else facing the same issues.

 And how to solve this ? @XiaoMi 

![WhatsApp Image 2019-11-30 at 12 47 53 PM (1)](https://user-images.githubusercontent.com/13750931/69897273-bcea7100-136f-11ea-9a20-87c58c45c187.jpeg)

![WhatsApp Image 2019-11-30 at 12 47 53 PM](https://user-images.githubusercontent.com/13750931/69897274-bf4ccb00-136f-11ea-83f8-3604621ec2f8.jpeg)

[MIUI11_Issues_video.zip](https://github.com/syssi/xiaomi_airconditioningcompanion/files/3906826/MIUI11_Issues_video.zip)

**Comment by syssi** [comment]
Why do you think this is the right place for your issue?
