### ISSUE TITLE
The AC isn't working as expected

### ISSUE THREAD

**Issue by X-Corde-Official** [syssi/xiaomi_airconditioningcompanion#93]
I configurated it as readme said, and the ac did show up in the home assistant panel. However, I can only control the on and off of the ac and can do nothing about temp or stuff like that. I was wondering if I can customize the ir code of the plug-in and edit it one by one until it function normally
but i dont know where to edit the IR command.

**Comment by X-Corde-Official** [comment]
如何自定义插件的红外码？？？

**Comment by syssi** [comment]
Are you able to control the AC via the MiHome App? How did you setup your AC there? Could you tell me the manufacturer and model of your AC?

**Comment by X-Corde-Official** [comment]
my ac is from gree and on mihome app i am able to control the ac and all function works perfectly
when i configure it on home assistant, it does appear but no matter what mode i entered it always become ey(auto mode) on the ac.

**Comment by X-Corde-Official** [comment]
on mihome app it said the ac is paired with code system: gree 10727, all functions work properly

**Comment by X-Corde-Official** [comment]
@syssi 
the ac is from Gree and it functions normally in MiHome App, however, I can only turn off the ac or set it to auto mode no matter what mode i set in HA .

**Comment by syssi** [comment]
I will close this issue because it's a duplicate: https://github.com/syssi/xiaomi_airconditioningcompanion/issues/51

I hope this issue can be fixed soon.
