### ISSUE TITLE
device not found or token incorrect

### ISSUE THREAD

**Issue by mouth4war** [syssi/xiaomi_airconditioningcompanion#94]
Hi @syssi I've got the latest miio release running with dev HASS core. Trying to add the acpartner v3 but keep getting this exception.

````
[miio.miioprotocol] Unable to discover a device at address 192.168.130.137
[custom_components.xiaomi_miio_airconditioningcompanion.climate] Device unavailable or token incorrect: Unable to discover the device 192.168.130.137

**Comment by mouth4war** [comment]
Token is from network info page. Hub wireless protocol is on but the gateway feature is not being used in HASS.

**Comment by syssi** [comment]
How did you solve the issue?
