### ISSUE TITLE
Request to add power consumption statistics

### ISSUE THREAD

**Issue by Stalker-404** [syssi/xiaomi_airconditioningcompanion#95]
Hi, I tried to calculate the power consumption by calculating the average of load_power, but the result was far from the Mi Home APP. I hope to add the daily power consumption and monthly power consumption statistics.

**Comment by hoanglongutc** [comment]
I have the same problem as you

**Comment by SPEC1AL1ST** [comment]
How can I see the power consumption?
The air conditioner is connected to the companion. The original app shows the power consumption.

**Comment by anhnvme** [comment]
extract low_power attr use this https://www.home-assistant.io/integrations/utility_meter/

**Comment by SPEC1AL1ST** [comment]
> extract low_power attr use this https://www.home-assistant.io/integrations/utility_meter/

Thank!

**Comment by syssi** [comment]
The power consumption is exposed as attribute `load_power` you have to add a template sensor to your configuration. This sensor entity can be fed the `utility_meter` component.

**Comment by Stalker-404** [comment]
> The power consumption is exposed as attribute `load_power` you have to add a template sensor to your configuration. This sensor entity can be fed the `utility_meter` component.

Thank you very much for your answer.  I have noticed `utility_meter` some time ago and it works successfully！
