### ISSUE TITLE
0.109.2版本的运行模式没有了。

### ISSUE THREAD

**Issue by wwwww911** [syssi/xiaomi_airconditioningcompanion#96]
![傲游截图20200504203707](https://user-images.githubusercontent.com/53208935/80966644-7978bf00-8e47-11ea-80a4-2b4c87078e3e.png)

但是依然可以点击，只是没有内容了，而且点了依然可以起作用。

之前的版本是0.105的时候是正常的。

**Comment by wwwww911** [comment]
今天升级了0.109.6就正常了。

**Comment by syssi** [comment]
Please clear your browser cache and try again.
