### ISSUE TITLE
Load_Power Show?

### ISSUE THREAD

**Issue by hoanglongutc** [syssi/xiaomi_airconditioningcompanion#99]
59/5000
Can you help me, showing load_power on the UI interface. Thanks
![Captusdfsafdre](https://user-images.githubusercontent.com/35026043/82779523-9751a680-9e7e-11ea-8611-2fe486c1fa8e.PNG)

**Comment by anhnvme** [comment]
use custom card to show power_load or create sensor from template

**Comment by hoanglongutc** [comment]
> use custom card to show power_load or create sensor from template

You can help yourself with a specific custom card example

**Comment by anhnvme** [comment]
> > use custom card to show power_load or create sensor from template
> 
> You can help yourself with a specific custom card example

Check it out 
https://github.com/nervetattoo/simple-thermostat

**Comment by hoanglongutc** [comment]
> > > use custom card to show power_load or create sensor from template
> > 
> > 
> > You can help yourself with a specific custom card example
> 
> Check it out
> https://github.com/nervetattoo/simple-thermostat

Thanks!

**Comment by SPEC1AL1ST** [comment]
How can I see the power consumption?
The air conditioner is connected to the companion. The original app shows the power consumption.
